<?php

/**
* Implementation of hook_views_pre_render
* This function is in place to filter out duplicate nodes
* from listings. It will cycle each result, and store a new array of
* unique NIDs, and when a duplicate is found, will unset that result
*
* Based on a pattern for reducing duplicate terms in a view
* (http://himerus.com/comment/158)
*
* @param $view
*/

function fieldglass_init() {

 /* drupal_add_js(' jQuery.browser = {};
(function () {
    jQuery.browser.msie = false;
    jQuery.browser.version = 0;
    if (navigator.userAgent.match(/MSIE ([0-9]+)\./)) {
        jQuery.browser.msie = true;
        jQuery.browser.version = RegExp.$1;
    }
})();', 'inline');
 */
    drupal_add_js( 'sites/all/modules/fieldglass/fieldglass.js');
    drupal_add_js( 'sites/all/libraries/sidr-package-1.2.1/jquery.sidr.min.js');
    if (current_path() == 'agenda' || current_path() == 'agenda-test' || current_path() == 'emea/agenda') {
        drupal_add_js( 'sites/all/modules/fieldglass/agenda.js');
    }
    drupal_add_css( 'http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css', 'theme');
}

function fieldglass_views_pre_render(&$view){
    //make company json view data compatible for data viz
    if ($view->name == "company_profile"){
        if ($view->current_display == "page_2" ) {
            foreach($view->result AS $k => $result){
                //make string into number
                if (isset($result->field_field_maturity[0]['rendered']['#markup'])) {
                    $result->field_field_maturity[0]['rendered']['#markup'] = (int)substr($result->field_field_maturity[0]['rendered']['#markup'], 0,1);
                }
                //swap mgmt model for #
                if (isset ($result->field_field_management_model[0]['rendered']['#markup'])) {
                    switch ($result->field_field_management_model[0]['rendered']['#markup']){
                        case "MSP":
                            $result->field_field_management_model[0]['rendered']['#markup'] = 1;
                            break;
                        case "Hybrid":
                            $result->field_field_management_model[0]['rendered']['#markup'] = 0;
                            break;
                        case "Self-managed":
                            $result->field_field_management_model[0]['rendered']['#markup'] = -1;
                            break;
                        default:
                            break;
                    }
                }
            }
        }
    }
}
